jobs:
  publish:
    stage: publish
    do:
      type: script
      env:
        INPUT: ${project.repos.main.path}/public
        HAKYLL_DESTINATION: ${project.data_path}/hakyll/site
        HAKYLL_STORE: ${project.data_path}/hakyll/store
        BUILDER: ${project.repos.main.path}/builder
        BUILDER_PROFILE: ${project.data_path}/builder

        MATOMO_HOST: matomo.iliay.ar
      script: |
        set -e
        . /etc/profile

        nix build $BUILDER#main-site --profile $BUILDER_PROFILE --no-link

        mkdir -p $HAKYLL_DESTINATION
        mkdir -p $HAKYLL_STORE

        cd $INPUT
        $BUILDER_PROFILE/bin/site build

stages:
  publish:
    on_overlap: cancel

integrations:
  github:
    token: ${project.secrets.github_token}
    repo: 'iliayar/iliayar'
    rev: ${project.repos.main.rev}
    ui_url: 'https://uci.iliay.ar'
    jobs_to_report:
    - publish
