caddy:
  enabled: true
  hostnames:
    'iliayar.ru': |
      redir https://iliay.ar{uri}

    'ilyay.space': |
      redir https://iliay.ar{uri}

    'iliay.ar': |
      file_server
      root * ${project.data_path}/gen-main

      @conspectsOldOrigin { 
        header Origin https://conspects.ilyay.space
      }
      header @conspectsOldOrigin Access-Control-Allow-Origin https://conspects.ilyay.space

      @conspectsOrigin { 
        header Origin https://conspects.iliay.ar
      }
      header @conspectsOrigin Access-Control-Allow-Origin https://conspects.iliay.ar

docker:
  volumes:
    main-org-publish-cache:

actions: ${${load(./actions.yaml)}.actions}

pipelines:
  publish-main: ${load(./publish_pipeline.yaml)}
