caddy:
  enabled: true
  hostnames:
    'iliayar.ru': |
      redir https://ilyay.space{uri}

    # FIXME: Move to main site repo
    'ilyay.space': |
      file_server
      root * ${project.data_path}/gen-main

      header Access-Control-Allow-Origin https://conspects.ilyay.space

docker:
  volumes:
    main-org-publish-cache:

actions: ${${load(./actions.yaml)}.actions}

pipelines:
  publish-main: ${load(./publish_pipeline.yaml)}
