caddy:
  enabled: true
  hostnames:
    'ilyay.space': |
      redir https://iliay.ar{uri}

    'iliay.ar': |
      file_server
      root * ${project.data_path}/hakyll/site

      @conspectsOrigin { 
        header Origin https://conspects.iliay.ar
      }
      header @conspectsOrigin Access-Control-Allow-Origin https://conspects.iliay.ar

actions: ${${load(./actions.yaml)}.actions}

pipelines:
  hakyll-main: ${load(./hakyll_pipeline.yaml)}
