caddy:
  enabled: true
  hostnames:
    'iliayar.ru': |
      redir https://ilyay.space{uri}

    # FIXME: Move to main site repo
    'ilyay.space': |
      file_server
      root * ${project.data.path}/gen-main

      header Access-Control-Allow-Origin https://conspects.ilyay.space
