#+OPTIONS: toc:nil

#+include: "brief.org"

[[file:../other/cv/cv.pdf][download cv]]

* general
22 y.o, located in Saint-Petersburg, Russia

* education
*ITMO University*, september 2019 - july 2024 \\
/B.S. in Computer Science/
- used to write conspects in \(\LaTeX\), all of this along with assignments is
  [[https://github.com/iliayar/ITMO][stored on github]]. Conspects are auto
  built and published on [[https://conspects.iliay.ar/README.html][separate
  site]]

* work experience
*Yandex Go*, november 2021 - /present/ \\
/Sotware Engineer/
- designed and implemented new Domain Specific, Python's expressions inspired
  Language and tooling for it, including translator from previously used DSL.
- worked out new way of deploying user's code, designed new gRPC service
  following Google's AIP.
- developing and maintaining couple high load widely used infrastructure
  microservices, written in C++ using /userver/ framework. 
- developed a type inference system for internally used DSL, OpenAPI schemas
  generator and tooling around. 

* projects
*uCI* \\
blazingly fast 🚀 
- completly [[https://github.com/iliayar/uci][opensource]]. simple and easy to use but at the same time
  enough powefull ci/cd system, intendent to use as self-hosted.

*UPA CAN FLASH*
- partially [[https://github.com/iliayar/UPA_CAN_FLASH][opensource]]. cross-platform gui application for flashing
  microcontrollers, that operates with ISO-14229. implement protocol
  from scratch up to abstraction of application layer.

* other interests
like [[https://ctftime.org/user/70331][playing ctfs]] sometimes. last couple years stick with pwn and
reverse, but used to other category, as was playing almost solo in the
beginning.

-----

in the past enjoyed tinkering with my [[https://github.com/iliayar/dotfiles][desktop setup]]. now settle up
with [[https://nixos.org/][nix]], as one of the most reproducible build system with wonderfull
configuration language and rich ecosystem. now using it everywhere for
setting up reproducible development evironment and system
configuration.

...
* links
github: [[https://github.com/iliayar][iliayar]] \\
linkedin: [[https://linkedin.com/in/iliayar][iliayar]] \\
telegram: [[https://t.me/iliayar][@iliayar]] \\
email: [[mailto:iliayar3@gmail.com][iliayar3@gmail.com]]

other fun links \\
code::stats: [[https://codestats.net/users/iliayar][iliayar]]
